### ISSUE TITLE
PM10 v. 10.0

### ISSUE THREAD

**Issue by bardcsl** [bardcsl/Continuous_Monitoring#4]
Hey @oroconnor Owen, 

Things are looking great! 

One issue I've come across in the purpleair data processing script is the use of PM10 for the _atm columns and 10.0 for the _CF1 columns. I think it has to do with the way the sensors output the data when you download from the website, but it ends up posing an issue down the line. If you are running the script for an indoor sensor, you have to make sure to edit the columns for PM10 during the averaging step to either have a ".0" appended or not. Its a small thing, but it's not sustainable to have that be an issue if we are trying to pass thie script down to folks after I leave who aren't aware of the sensor's quirks. It may be a matter of  just having a step in the code where all PM column headers are modified to have  a ".0" on the end regardless of which sensor they are coming from. Does this make sense? Let me know if I can clarify better.

**Comment by oroconnor** [comment]
@bardcsl 

I believe I understand the issue. The raw data files have the CF1 number labelled as PM10.0 and the ATM number labelled as PM10.
When I was averaging them in line 209, I did not include the .0
I have corrected that, I believe and updated script. It is possible that this difference becomes the source of other confusions, in which case I could go through and change the variable names to be consistent from the start.
